### PR TITLE
[qbatteryinfo] statefs-based implementation

### PR DESCRIPTION
**Pull request by deztructor**
Signed-off-by: Denis Zalevskiy denis.zalevskiy@jolla.com

### CODE REVIEW

**Comment by lpotter** [comment]
What's wrong with the current implementations? i.e. why would we need this instead?

Doesn't this just make qsysteminfo a wrapper around a wrapper of udev?

As well, this needs to be upstreamed first.

**Comment by deztructor** [comment]
We are getting rid of upower.

Contextkit/statefs abstracts the way information is retrieved.

No, I do not want to spend time for upstreaming, this is the plugin for Mer only.

**Comment by deztructor** [comment]
As also there is no reason to duplicate udev->power_properties logic already implemented in the statefs provider.

**Comment by lpotter** [comment]
All Qt things need to be upstreamed. Upstream has ssu so statefs for mer is ok.

**Comment by lpotter** [comment]
https://codereview.qt-project.org/#/c/105795/
Change-Id: Ib1fc4a3034415be65a72ad0005cf625bf54b4eca

**Comment by lpotter** [comment]
LGTM

**Comment by deztructor** [comment]
Separated to 2 commits: Mer spec changes commit and implementation. Also changed according to upstream review (https://codereview.qt-project.org/#/c/105795/1//ALL,unified): removed redundant PropertyInfo, used newly added statefs properties to properly set capacity props

**Comment by lpotter** [comment]
LGTM

**Comment by rburchell** [comment]
i'll take this as-is for now. as bernd asked, please focus on the upstream change and get this in there, or it will be lost/reverted in the future

**Pull request merged**
